name: Create manual release

on:
  workflow_dispatch:
    inputs:
      release_version_tag:
        description: 'Unique release version (generates tag)'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild eqgame_dll.sln /p:Configuration=Release /p:Platform=Win32

      - name: Create the github release tag and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./Release/eqgame.dll,./Release/eqgame.pdb"
          artifactErrorsFailBuild: true
          commit: ${{ github.sha }}
          tag: ${{ github.event.inputs.release_version_tag }}
